### ISSUE TITLE
Delete repo

### ISSUE THREAD

**Issue by GreenDude120** [Decker87/gdrive-alfred#1]
Hi. You have a repo under your username that I created with my friend a long time ago. My friend deleted the repo so I had to recreate it. But because you had forked or something, it still exists under your name. 

https://github.com/Decker87/Path-of-Diablo-Launcher this is the repo. 

this is the official one that i had reuploaded shortly after: https://github.com/GreenDude120/PoD-Launcher

Some of our players are still finding yours by accident instead of ours so I was wondering if you could please delete yours.

Thank you very much. Sorry about contacting you through this ticket but since github has no PMs, i didn;t know how else to reach you.

**Comment by Decker87** [comment]
Hey, sure thing. I forked it a long time ago to play around with the code. I've gone ahead and deleted it.

**Comment by GreenDude120** [comment]
Thanks a ton man. Feel free to delete this Issue . Sorry about dropping in on a random repo. Thanks again
